### ISSUE TITLE
Questions about the paper and inputs to the method

### ISSUE THREAD

**Issue by johnwlambert** [senthilps8/avmap#1]
Hi, thanks for sharing your code and very nice work on your paper.

I was trying to understand a bit more about the inputs to the network.
1. Do the audio-visual models assume known camera intrinsics?
2. Is relative pose between the images assumed to be known, or is this inferred?
3. How are predictions from all time steps aggregated?

Could you explain the assumptions about the available inputs in a bit more detail?

**Comment by senthilps8** [comment]
Hi John

1.  We don't explicitly provide the camera intrinsics to the model. However, all our simulation data was generated from the habitat renderer which has fixed intrinsics. It doesn't change across the videos/trajectories. So the model could be implicitly learning these parameters.
2.  The relative pose change is assumed to be known. 
3. The predictions from all the time steps are just max-pooled. This is possible because the global alignment of these predictions happens at the feature level. In this image below (taken from the paper), you can see we use $r_2$ and $r_3$ to align the features based on the movement that happened by rotating and translating the features accordingly. 
![image](https://user-images.githubusercontent.com/9179485/140396239-02ff6b02-4755-45bf-a48e-90c1ccee7dfa.png)

Hope that answers your questions!

**Comment by johnwlambert** [comment]
Got it, thank you.
